pip install numpy - For local system usage.

In [ ]:
import numpy as np

In [ ]:
a = [1, 2, 3, 4, 5]
type(a)

list

In [ ]:
b = [i*i for i in a]
print(b)

[1, 4, 9, 16, 25]


In [ ]:
# x = np.array([1, 2, 3, 4, 5])
x = np.array(a)
type(x)

numpy.ndarray

In [ ]:
y = x ** 2
print(y)

[ 1  4  9 16 25]


In [ ]:
# %timeit

l = range(2000000)
%timeit [i**2 for i in l]

801 ms ± 203 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
t = np.array(range(2000000))
%timeit t**2

2.21 ms ± 296 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
801 / 2.21

362.4434389140272

In [ ]:
print(x)

[1 2 3 4 5]


In [ ]:
x.ndim

1

In [ ]:
x.shape

(5,)

In [ ]:
x2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(x2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
x2.ndim

2

In [ ]:
x2.shape

(4, 3)

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

1 (8,)


In [ ]:
x3 = np.array([[1, 2, 3, 4, 5], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(x3)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [ ]:
t3 = np.array([[[1, 2], [1, 2], [2, 3]], [[1, 2], [1, 2], [2, 3]], [[1, 2], [1, 2], [2, 3]]])
print(t3)

[[[1 2]
  [1 2]
  [2 3]]

 [[1 2]
  [1 2]
  [2 3]]

 [[1 2]
  [1 2]
  [2 3]]]


In [ ]:
t3.ndim

3

In [ ]:
t3.shape

(3, 3, 2)

In [ ]:
a = range(5)
for i in a:
  print(i)

0
1
2
3
4


In [ ]:
# range(start, end, jump) / range(start, end, step-size)
b = range(5, 100, 5)
print(list(b))

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]


In [ ]:
c = np.arange(5, 100, 5)
print(c)

[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
# numpy arange allow float data type for jump / step-size
c = np.arange(5, 10, 0.5)
print(c)

[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [ ]:
s = np.array(["Hi", "How", "Are", "you"])

In [ ]:
print(s)

['Hi' 'How' 'Are' 'you']


In [ ]:
l = [1, 2, 3, 4, 5, 6]
a = np.array(l)
print(a)

[1 2 3 4 5 6]


In [ ]:
l = [1, 2, 3, 4, 5.0, 6]
a = np.array(l)
print(a)

[1. 2. 3. 4. 5. 6.]


In [ ]:
l = [1, 2, "Amrit", 4, 5.0, 6]
a = np.array(l)
print(a)

['1' '2' 'Amrit' '4' '5.0' '6']


In [ ]:
l = [1, 2, 3, 4, 5.0, 6]
a = np.array(l, dtype = int)
print(a)

[1 2 3 4 5 6]


In [ ]:
l = [1, 2, "Amrit", 4, 5.0, 6]
a = np.array(l, dtype = int)
print(a)

ValueError: invalid literal for int() with base 10: 'Amrit'

In [ ]:
l = [1, 2, 3, 4, 5.0, 6]
a = np.array(l, dtype = int)
print(a)

[1 2 3 4 5 6]


In [ ]:
b = a.astype(float)

In [ ]:
print(b)

[1. 2. 3. 4. 5. 6.]


In [ ]:
l = [1, 2, "Hello", 4, 5.0, 6]
a = np.array(l)
print(a)

['1' '2' 'Hello' '4' '5.0' '6']


In [ ]:
a.astype(int)

ValueError: invalid literal for int() with base 10: 'Hello'

In [ ]:
l = [-2, 0, 3, 5, -1, 0]
a = np.array(l, dtype = bool)
print(a)

[ True False  True  True  True False]


In [ ]:
l = [-2, 0, 3, 5, -1, 0]
print(l[0])

-2


In [ ]:
print(l[3])

5


In [ ]:
a = np.array(l)
print(a)

[-2  0  3  5 -1  0]


In [ ]:
print(a[0])

-2


In [ ]:
print(a[3])

5


In [ ]:
print(a[-1])

0


In [ ]:
print(l[[2, 4]])

TypeError: list indices must be integers or slices, not list

In [ ]:
print(a)

[-2  0  3  5 -1  0]


In [ ]:
print(a[[2, 4]])

[ 3 -1]


In [ ]:
# a[ list of index ]
# a[2, 4] => invalid
# a[[2, 4]] => valid

print(a[2, 4])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
lst = [1, 4, 2, 1]
print(a[lst])

[ 0 -1  3  0]


In [ ]:
lst = [0, -1]
print(a[lst])

[-2  0]


In [ ]:
lst = [0, 100]
print(a[lst])

IndexError: index 100 is out of bounds for axis 0 with size 6

In [ ]:
print(l)

[-2, 0, 3, 5, -1, 0]


In [ ]:
m1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
print(m1[0:5])

[1 2 3 4 5]


In [ ]:
# a[start : end : jump]
print(m1[3 : 6 : 2])

[4 6]


In [ ]:
print(m1[6 : 0 : -2])

[7 5 3]


In [ ]:
print(m1[::-1])

[10  9  8  7  6  5  4  3  2  1]


In [ ]:
a = np.array([0,1,2,3,4,5])
a[4:] = 10
print(a)

[ 0  1  2  3 10 10]


In [ ]:
m1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(m1)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
m1 < 6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [ ]:
m1 % 2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [ ]:
a = np.array([-1, 3, 100, -5, -20, 53, 28])
lst = [True, True, True, False, False, True, False]
print(a[lst])

[ -1   3 100  53]


In [ ]:
print(a)

[ -1   3 100  -5 -20  53  28]


In [ ]:
a < 0

array([ True, False, False,  True,  True, False, False])

In [ ]:
a[ a < 0 ]

array([ -1,  -5, -20])

In [ ]:
a[a > 10]

array([100,  53,  28])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])
a[2:] = b[::-1]
print(a)

[1 2 6 7 8]


In [ ]:
# https://drive.google.com/file/d/1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK/view
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 13.1MB/s]


In [ ]:
score = np.loadtxt('survey.txt', dtype ='int')

In [ ]:
cnt = len(score)

In [ ]:
p = score[score >=9 ]
len(p)

609

In [ ]:
d = score[score < 7]
len(d)

332

In [ ]:
promoters = len(p) / cnt * 100
detractors = len(d) / cnt * 100
nps = promoters - detractors
print(nps)

23.73607540702657


In [ ]:
print(round(nps, 2))

23.74


In [ ]:
a = [10, 20, 30, 40, 50]
# 0, 1, 2, 3, 4
# -5, -4, -3, -2, -1

print(a[2])
print(a[-3])

30
30


In [ ]:
score[-5:-2]

array([ 1, 10,  5])

In [ ]:
# [start, end, jump]
score[-5:-2:-1]

array([], dtype=int64)

In [ ]:
score[-5:]

array([ 1, 10,  5,  9, 10])

In [ ]:
score[-2:-5:-1]

array([ 9,  5, 10])

In [ ]:
score[:20]

array([ 7, 10,  5,  9,  9,  4,  7,  9,  9,  9, 10,  4,  9,  9,  7, 10,  5,
        9,  7,  9])